### PR TITLE
changes to handle all of the suggested test cases together with a tes…

### PR DESCRIPTION
**Pull request by pblattnerjr**
…t case file for testing.

### CODE REVIEW

**Comment by pblattnerjr** [comment]
Michael,  with this pull request, the code handles all of the test cases correctly.  Changes are indicated by comments in the output file and hopefully contain enough information to trace how the updates occurred.

I think that there are two more steps that I can take.

1) run the test against the full file which I will once again download.

2) consider adding a switch to suppress the added comments to create a clean file for update purposes.

Paul

**Comment by mcolburn** [comment]
Hi, Paul!

Both ideas sound good to me!  I have not yet pulled your changes.  I have finally completed the first draft of the dissertation, and I am writing a summary to include when I send it to my main professor.

I should submit it within the next couple of days, then I plan to write a report of my research for OCMC and a version for overseas Hierarchs, e.g. His Eminence Makarios of Kenya.

Then, I will devote most of my time to programming, until I hear back from my professors.  I think it might be a long time.

Thanks for your help!

-Michael

**Comment by pblattnerjr** [comment]
Michael,

Congratulations on your dissertation milestone!

I'll get on the suggested steps today.

I have been spending time trying to come up with a short term contract to
build a little extra income but nothing has developed yet.  Note: I am not
looking that hard.  I like retirement.

Please be thinking of where I should help next.  I really like Go!

Paul

**Comment by mcolburn** [comment]
I will come up with a list of projects and let you pick the one that interests you the most.

**Comment by mcolburn** [comment]
Merging changes from Paul Blattner for ares file cleanup

**Comment by mcolburn** [comment]
Merged new pkg for cleaning ares files written by Pau Blattner

**Pull request merged**
